"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 100
command_timeout = 100

[git_status]
format = '([$all_status$ahead_behind]($style) )'
up_to_date = "[âœ“](green)"
# disabled = true

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'
